config/routes.rb
Lugogram::Application.routes.draw do
  resources :users do
    member do
      post :friend, :unfriend
      post :invite
    end
  end  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:show, :create, :destroy]

  root to: 'users#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/login',   to: 'sessions#create'
  match '/signout', to: 'sessions#destroy'
  match '/home',    to: 'users#home'
  match '/about',   to: 'static_pages#about'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :avatar, :password, :password_confirmation
  has_secure_password
  has_many :microposts
  has_many :friends, foreign_key: "user_id", dependent: :destroy


  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  

  def share(post)  
    #Send notifications
    post.getVisibility().each do |u|
      if self.id != u.id 
        UserMailer.lugogram_email(post, self, u).deliver unless u.admin?
      end
    end        
  end  

  def hasDefaultAvatar?
    self.avatar == nil or self.avatar.length == 0
  end
      
  def getAvatarURL
    if hasDefaultAvatar?
      "/images/glyphicons_003_user.png"
    else
      avatar
    end
  end


  def getFriends
    returnUsers = []
    friends.each do |u|
      user = User.find_by_id(u.friend_id)
      if user == nil #if the user has been deleted in the meanwhile
        u.destroy #remove the friend
      else
        returnUsers.push(user)
      end  
    end
    returnUsers
  end 

  def isFriend?(other_user)
    if self.id == other_user.id
      true
    else    
      friends.find_by_friend_id(other_user.id)   
    end  
  end

  def addFriend(other_user)
    if !isFriend?(other_user)
      friends.create!(friend_id: other_user.id) unless self.id == other_user.id  
    end
  end

  def removeFriend(other_user)
    friends.find_by_friend_id(other_user.id).destroy
  end

  def getHistory
    post_ids = %(SELECT micropost_id FROM eyes WHERE user_id = :user_id)
    Micropost.where("id IN (#{post_ids}) or user_id = :user_id", { user_id: self })
  end 

  def getVisiblePosts(other_users)
    if other_users != nil
      visible = other_users.clone
      visible.push(self)
      Micropost.joins(:eyes).where(:eyes => {:user_id => visible}).group("microposts.id").having("COUNT(*) = ?", visible.length)
    end  
  end 

  def hasNotLoggedIn
    self.name == self.email
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :index

  def home
    if signed_in?
      @micropost = current_user.microposts.build if signed_in?
      @friend  = User.new()
      @friends = current_user.getFriends
      @visible_users = []
      @microposts = nil
      visible_ids = params[:ids]
        
      if visible_ids != nil
        visible_ids.each do |id|
          @visible_users.push(User.find(id)) unless current_user.id.to_s == id
        end
        @microposts = current_user.getVisiblePosts(@visible_users)    
      else
        @microposts = current_user.getHistory
      end 
    end  
  end

  def edit
    @micropost = current_user.microposts.build #remove later
    
    @user = User.find(params[:id])
    @friend  = User.new()
    @friends = @user.getFriends
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @micropost = current_user.microposts.build #remove later
    @friend  = User.new() #remove later
    @friends = current_user.getFriends #remove later
    @visible_users = [] #remove later

    @users = User.all
  end

  def new
    @user = User.new(params[:user])
  end

  def create
    @user = User.new(params[:user])
    existing_user = User.find_by_email(@user.email.downcase)
    if existing_user
       if existing_user.hasNotLoggedIn
          if existing_user.update_attributes(params[:user])
            sign_in existing_user
            sendWelcomeMessage(existing_user) 
            flash[:success] = "Welcome to Lugogram! " + existing_user.name
            redirect_to root_url 
          end   
       else
        render 'new'
      end 
    else  
      if @user.save
        sign_in @user
        sendWelcomeMessage(@user) 
        flash[:success] = "Welcome to Lugogram! " + @user.name
        redirect_to root_url
      else
        render 'new'
      end
    end
  end

  

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile updated"
    end
    redirect_to root_url
  end

  def destroy
    User.find(params[:id]).destroy 
    redirect_to root_url
  end  

  def friend
    @userToFriend = User.find(params[:friend_id])
    current_user.addFriend(@userToFriend)
    #flash[:success] = "Friend added " + @userToFriend.name
    redirect_to root_url 
  end
    
  def unfriend
    @userToUnFriend = User.find(params[:friend_id])
    current_user.removeFriend(@userToUnFriend)
    #flash[:success] = "Friend removed " + @userToUnFriend.name
    redirect_to root_url
  end

  def invite
    @user = User.new(params[:user])
    existing_user = User.find_by_email(@user.email.downcase)
    if existing_user
      if current_user.isFriend?(existing_user)
        flash[:success] = "You are already friends with " + existing_user.name  + " :)" 
      else  
        flash[:success] = "You are now friends with " + existing_user.name  + " :)"
        current_user.addFriend(existing_user) 
      end  
    else  
      @user.name = @user.email.downcase
      @user.password = "guest123"
      @user.password_confirmation = @user.password
      if @user.save
        current_user.addFriend(@user) 
        @user.addFriend(current_user)           #this should be removed later
        flash[:success] = @user.email + " added."
      end
    end  
    redirect_to root_url
  end  


  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    def sendWelcomeMessage(user)
      # Send welcome message from Lugogram Staff:
      admin = User.find(1)
      post = admin.microposts.build()
      post.content = "Welcome to Lugogram " + user.name + "!"
      
      if post.save  
        #Set visibility
        visible = []
        visible.push(user)
        visible.push(admin)
        post.setVisibility(visible)
        admin.share(post) 
      end  
    end
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=20"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/edit.html.erb
<script>
    

    function checkImageURL(){
      var imageurl = document.getElementById("user_avatar").value;
      if (imageurl.length == 0){
        document.getElementById("avatar_preview").src = "<%=defaultAvatar%>";
      }else{
        $("<img>", {
            src: imageurl,
            error: function() { 
              alert("Avatar link is not working :( Try again or leave empty.");
            },
            load: function() { 
              document.getElementById("avatar_preview").src = imageurl;
            }
        });
      }
    }

   
</script>


<div class="well">
<h4>Settings</h4>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :avatar %>
  <div class="row-fluid">
  <div class="span6"><%= f.text_field :avatar, placeholder: "www...link to image (or leave empty)", onBlur: "checkImageURL()" %></div> 
  <div class="span2"><%= image_tag(current_user.getAvatarURL, :id => "avatar_preview", :size => "30x30") %></div>
  
  </div> 

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

<br/>
<%= link_to "Sign Out", signout_path, method: "delete" %>
<br/><br/>
<%= link_to "Delete my account", @user, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: @user.name %>
</div>

app/views/users/home.html.erb
<% if signed_in? %>
 


<% if @visible_users.length > 0 %>
<div class="well" style="padding:5px;">
  
  <div class="row-fluid" style="margin:0px;padding:0px;">
      
      <div class="span12"><a href="<%=root_path%>"><%= image_tag("glyphicons_192_circle_remove.png", style: "margin-left:20px;", size: "20x20")%></a></div>         
  </div>
  
  <ul class="thumbnails" style="margin:0px;padding:0px;border:0px">
    <li class="span4">
      <div class="thumbnail" style="margin:0px;padding:0px;border:0px;">
        <% if current_user.hasDefaultAvatar? %>
          <%= image_tag(current_user.getAvatarURL, :size => "40x40") %>   
        <% else %>
          <%= image_tag(current_user.getAvatarURL, :size => "40x40", class: "avatar_with_border") %> 
        <% end %>
        <h5 style="text-align:center;">You</h5>
      </div>
    </li>
    <% @visible_users.each do |u| %> 
      <li class="span4">
        <div class="thumbnail" style="margin:0px;padding:0px;border:0px;">
          
          <% if u.hasDefaultAvatar? %>
            <%= image_tag(u.getAvatarURL, :size => "40x40") %>   
          <% else %>
            <%= image_tag(u.getAvatarURL, :size => "40x40", class: "avatar_with_border") %> 
          <% end %>

            <h5 style="text-align:center;"><%=u.name%></h5>   
            <% if !@friends.include?(u) %>
              <span style="text-align:center;">
                <%= form_for u, url: {id: current_user.id, action: "invite"}, html: {method: :post} do |f| %>
                  <%= f.hidden_field :email, value: u.email %>
                  <%= f.submit "Add", class: "btn" %>
                <% end %> 
              </span>  
            <% end %> 
        </div>
      </li>  
    <% end %>            
  </ul> 
  </div>   

  <% else %>
    <div id="tooltip" ></div>
  <% end %>

  <div id="mobileInsert" ><div class="accordion-group" style="border:0;padding:0;margin:0">
  
  <% 
  messageClass = "collapse"
  if @visible_users.length > 0 
    messageClass = "collapse in"
  end 
  %>  

    <div id="newMessage" class="<%=messageClass%>"><div class="well" style="padding: 5px;">  
  <%= form_for(@micropost) do |f| %>  
  <div class="modal-header">
    <h4 id="friendModalLabel">New message <% if (@visible_users != nil and !@visible_users.empty?) %> in this group <% end %></h4>
  </div>
  <div class="modal-body" style="padding: 0px;">
    <ul class="nav nav-list">  
        
      <%= f.hidden_field :weblink %>
      <%= f.hidden_field :imagelink %>
      <li><%= render 'shared/error_messages', object: f.object %></li>   
      <li class="nav-header">Message</li>
      <li>
        <%= f.text_area :content, rows: "2", placeholder: "Dont forget to buy milk!", maxlength: "100" %>
      </li>

      <li class="nav-header" >
        <div class="row-fluid"><a data-toggle="collapse" data-target="#linkcollapse" role="button" class="noline"><%= image_tag("glyphicons_050_link.png", size: "16x16")%> Add link (optional)</a>
          <div id="linkcollapse" class="collapse">
                 
          <table>
            <tr><td><input type="text" id="url" name="url" placeholder="www..." maxlength="100" /></td>
            <td valign="top"><button class="btn" type="button" onClick="makeShort()">Shorten</button></td>
          </tr>
          <tr>
            <td><input type="dropbox-chooser" name="selected-file" id="db-chooser" /></td> 
          </tr>  
        </table>  
        </div>
        </div>  
      <li>
            
      <% if @visible_users == nil or @visible_users.empty? %>
        <li class="nav-header">Visible to</li>
        <li><table>
          <tr>
          <td colspan="2" nowrap><img src="<%=current_user.getAvatarURL%>" class="avatar_selected" width="24" height="24"><span class="name_selected"> You</span></td>
          </tr>
        <%  @friends.each do |u| %>          
          <tr>
          <td colspan="2" nowrap><div onClick=buttonPress('<%=u.id%>')><img src="<%=u.getAvatarURL%>" id="image_<%=u.id%>" class="avatar_unselected" width="24" height="24"><span id="name_<%=u.id%>" class="name_unselected"> <%= u.name %></span></div></td>               
          <input type="hidden" id="friends[<%=u.id%>]" name="friends[<%=u.id%>]" value="false"/> 
          </tr>
        <% end %>
        </table></li> 
      <% else %>
          <%  @visible_users.each do |u| %>
            <input type="hidden" id="friends[<%=u.id%>]" name="friends[<%=u.id%>]" value="true"/> 
         <% end %> 
      <% end %>           
  </br>
  </div> 
  <div class="modal-footer">
      <button class="btn" type="button" data-toggle="collapse" data-parent="#mobileInsert" data-target="#newMessage" >Close</button>
      <%=f.submit "Share", class: "btn btn-success" %>
    </div> 
    
  <% end %>
  </div></div>

  <div id="addFriend" class="collapse"><div class="well" style="padding: 5px;">   
  <div class="modal-header">
    <h4 id="friendModalLabel">Friends</h4>
  </div>
  <div class="modal-body" style="padding: 5px;">
    <ul class="nav nav-list" style="padding: 0px;">
      <li><table>
        <% @friends.each do |u| %> 
          <tr>
          <td valign="top"><%= image_tag(u.getAvatarURL, size: "24x24") %> <%= u.name %> </td> 
          <td valign="top"><%= button_to "Remove", {id: current_user.id, friend_id: u.id, controller: "users", action: "unfriend"}, class: "btn btn-mini" %></td> 
          </tr> 
        <% end %>
    </table></li>
  </ul>
  <%= form_for @friend, url: {id: current_user.id, action: "invite" } do |f| %>
    <ul class="nav nav-list"> 
      <li><span class="nav-header">Add someone</span><span style="font-size: 10px;color: gray;"> Your friend wont get notified until you send him/her a message.</span></li>
      <li><%= f.email_field :email, placeholder: "Email" %></li>
    </ul>
  </div>  
  <div class="modal-footer">
    <button class="btn" type="button" data-toggle="collapse" data-parent="#mobileInsert" data-target="#addFriend">Close</button>
    <%= f.submit "Add", class: "btn btn-success" %>
  </div>  
  <% end %>
</div></div>

<div id="settings" class="collapse"><div class="well" style="padding: 5px;">   
  <%= form_for(current_user) do |f| %>
  <div class="modal-header">
    <h4 id="settingsModalLabel">Settings</h4>
  </div>
  <div class="modal-body" style="padding: 0px;">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :avatar %>
    <div class="row-fluid">
    <div class="span8"><%= f.text_field :avatar, placeholder: "www...link to image (or leave empty)", onBlur: "checkImageURL()" %></div> 
    <div class="span4"><%= image_tag(current_user.getAvatarURL, :id => "avatar_preview", :size => "30x30") %></div>
    </div> 

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>


    <%= link_to "Sign Out", signout_path, method: "delete" %>
    </br>
    <%= link_to "Delete my account", current_user, method: :delete,
                                         data: { confirm: "You sure?" },
                                         title: current_user.name %>
    </div>
     <div class="modal-footer">
    <button class="btn" type="button" data-toggle="collapse" data-parent="#mobileInsert" data-target="#settings">Close</button>
    <%= f.submit "Save changes", class: "btn btn-success" %>
    </div>
                                 
  <% end %>
</div></div>

</div>
</div>

  <div>
    <%  @microposts.each do |micropost| %> 
      <div class="row-fluid">
      <div class="span12">
      <%= render micropost %>
      </div> 
     </div>  
    <% end %>
  </div>


<% else %>
  <div class="center hero-unit" style="background-color: #ffffff;margin-left:0px;margin-right:0px;">
    <h1>Private sharing: faster</h1>     
    <p>
      All messages on Lugogram are private to and from your close friends. Not companies. Not ads. Not old school mates. 
      The contents of messages are private forever (and will never be used to target adverticing).
    </p>
    </br>
    <p>Its a lot like email but easier to use: Private sharing the way it's suppose to be.</p>
    <p><%= link_to "Sign up now, it's free", signup_path, class: "btn btn-large btn-success" %></p> 
  </div>
  <div class="row-fluid">
  <%= render 'shared/lugogram_message', avatar: defaultAvatar, name: 'Julia', time: "", visibility: "", message:'Thanks for the dinner yesterday, the food was fantastic!', weblink: "", imagelink: "", color: randomColor() %>
  <%= render 'shared/lugogram_message', avatar: defaultAvatar, name: 'Lisa', time: "", visibility: "", message:'We are leaving for the pizza place now, feel free to join.', weblink: "", imagelink: "", color: randomColor() %>
  <%= render 'shared/lugogram_message', avatar: defaultAvatar, name: 'Ben', time: "", visibility: "", message:'Dont forget the milk!', weblink: "", imagelink: "", color: randomColor() %> 
  <%= render 'shared/lugogram_message', avatar: defaultAvatar, name: 'Martin', time: "", visibility: "", message:'Bootstrap link: http://twitter.github.io/bootstrap/components.html#thumbnails', weblink: "", imagelink: "", color: randomColor() %>
  </div>
<% end %> 

app/views/users/index.html.erb
<h1>All users</h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= image_tag(user.getAvatarURL, :size => "24x24") %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password, "Password (minimum 6 characters)"  %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm password" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/show.html.erb
<div class="hero-unit">
	<%= image_tag(@user.getAvatarURL, size: "48x48") %>
	<h2><%=@user.name%></h2>
		<% if(current_user.isFriend?(@user)) %>
			<p>Email: <%=@user.email%> (visible to friends) </p>
		<% end %>
	
	</br>Joined lugogram as number <%=@user.id%>
	</br><%=@user.microposts.length%> messages sent, <%=@user.getHistory.length%> recieved
		
	</br></br>
	<% if(@user.id == current_user.id) %>
	

	<% else %>
		<% if(!current_user.isFriend?(@user)) %>		
			<%= button_to "Add as a friend", {friend_id: @user.id, controller: "users", action: "friend"}, class: "btn btn-primary" %>

		<% else %>
			<%= button_to "Remove as a friend", {friend_id: @user.id, controller: "users", action: "unfriend"}, class: "btn btn-primary" %>
		<% end %>
		<% if(current_user.admin) %>
			<br/><button class="btn" type="button"><%= link_to "Delete user", @user, method: :delete,
	                                     data: { confirm: "You sure?" },
	                                     title: @user.name %></button>
			<% end %>
	<% end %>
</div>