config/routes.rb
Lugogram::Application.routes.draw do
  resources :users do
    member do
      post :friend, :unfriend
      post :invite
    end
  end  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:show, :create, :destroy]

  root to: 'users#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/login',   to: 'sessions#create'
  match '/signout', to: 'sessions#destroy'
  match '/home',    to: 'users#home'
  match '/about',   to: 'static_pages#about'
  

end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Lugogram</title> 
    <%= favicon_link_tag %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="https://apis.google.com/js/client.js"> </script>  
    <script type="text/javascript" src="https://www.dropbox.com/static/api/1/dropins.js" id="dropboxjs" data-app-key="s0y1a8bft03ts1x"></script>       

    <script>
      
    $(document).ready(function() {
      
      $('#tooltip').click(function(){
        $('#tooltip').remove(); 
        $.cookie("tip_reply_read", "true", { expires: 7 }); 
        return false;
      });

      $('#newMessage').on('show', function () {
        loadDropBoxListener();
        loadURLShortener(); 
      })
      
    });
    
  function buttonPress(userID){      
    var friend_id = "friends[" + userID + "]";
    var image_id = "image_"  + userID;
    var name_id = "name_"  + userID;
    //var select_id = "select_"  + userID;

    var visible = document.getElementById(friend_id).value;
    if(visible == "false"){        
      document.getElementById(image_id).setAttribute("class", "avatar_selected");   
      document.getElementById(name_id).setAttribute("class", "name_selected");
     // document.getElementById(select_id).setAttribute("class", "avatar_selected");       
      document.getElementById(friend_id).value = "true";
    }else{ 
      document.getElementById(image_id).setAttribute("class", "avatar_unselected");
      document.getElementById(name_id).setAttribute("class", "name_unselected"); 
     // document.getElementById(select_id).setAttribute("class", "avatar");
      document.getElementById(friend_id).value = "false";
    }  
  }
  

  function checkImage(){
    var imageurl = document.getElementById("imageurl").value;
    $("<img>", {
        src: imageurl,
        error: function() { 
          document.getElementById("imageurl").value = "Image link is not working :(";
        },
        load: function() { 
          document.getElementById("imageurl").value = "Image OK";
          document.getElementById("micropost_imagelink").value = imageurl;
        }
    });
  }

  function checkImageURL(){
      var imageurl = document.getElementById("user_avatar").value;
      if (imageurl.length == 0){
        document.getElementById("avatar_preview").src = "<%=defaultAvatar%>";
      }else{
        $("<img>", {
            src: imageurl,
            error: function() { 
              alert("Avatar link is not working :( Try again or leave empty.");
            },
            load: function() { 
              document.getElementById("avatar_preview").src = imageurl;
            }
        });
      }
    }


  function makeShort() {       
    var longUrl = document.getElementById("url").value;      
    if (longUrl != null && longUrl.length > 0){
        var request = gapi.client.urlshortener.url.insert({
          'resource': {
          'longUrl': longUrl
        }
        });
        request.execute(function(response){    
            if(response.id != null){                
                document.getElementById("url").value = response.id;
                document.getElementById("micropost_weblink").value = response.id;
                
            }else{
              //alert('urlshorten failed');              
              document.getElementById("micropost_weblink").value = longUrl; 
            }
        });
      }
   }

  function loadDropBoxListener(){   
    document.getElementById("db-chooser").addEventListener("DbxChooserSuccess",
      function(e) {
          document.getElementById("url").value = e.files[0].link;
      }, false);
  } 

  function loadURLShortener(){
      //Get your own Browser API Key from  https://code.google.com/apis/console/
      gapi.client.setApiKey('AIzaSyCF1DzfpTiMuzKk2TjudaZ-bPIPGjaL6NY');
      gapi.client.load('urlshortener', 'v1',function(){});
      
  }

  function loadToolTip(){
    var checkedToolTip = $.cookie("tip_reply_read");
    if (checkedToolTip == null){
      $('#tooltip').append('<div id="alert" class="alert alert-info"><div id="tooltipDismiss" type="button" class="close">&times;</div><strong>Tip: </strong> Click on a message to reply</div>');
    }
  }
  
  function load(){ 
    loadToolTip();   
  }
  window.onload = load;
   
</script>

</head>
<body>
<div class="container-fluid"> 
    <div class="row-fluid">   
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container-fluid">
              <%= link_to "lugogram", root_path, class: "brand" %>             
              <% if signed_in? %>
                <ul class="nav pull-right">    
                  <li><a data-toggle="collapse" data-parent="#mobileInsert" data-target="#newMessage" role="button" ><%= image_tag("glyphicons_010_envelope.png", :size => "28x28") %></a></li> 
                  <li><a data-toggle="collapse" data-parent="#mobileInsert" data-target="#addFriend" role="button" ><%= image_tag("glyphicons_006_user_add.png", :size => "28x28") %></a></li>
                  <li><a data-toggle="collapse" data-parent="#mobileInsert" data-target="#settings" role="button" >   
                    <% if current_user.hasDefaultAvatar? %>
                      <%= image_tag(current_user.getAvatarURL, :size => "24x24") %>   
                    <% else %>
                      <%= image_tag(current_user.getAvatarURL, :size => "20x20", class: "avatar_with_border") %> 
                    <% end %>
                  </a></li>
                </ul>
              <% else %>
                  <ul class="nav pull-right"> 
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Sign in", signin_path %></li>
                  </ul>
             <% end %>
            </div>
          </div>
        </div>
        <div class="visible-desktop" style="padding-top: 90px;"></div>  
      </div>
      <div class="row-fluid"> 
      <div class="span1"></div>  
        <div class="span10">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
        </div>
        <div class="span1"></div>
    </div> 
  </div>   
</body>
</html>

app/views/layouts/cute.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <style type="text/css">
      .a {
        color: black; 
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <%= render 'shared/lugogram_message', avatar: @lugogram_avatar, name: @lugogram_name, time: "", visibility: "", message: @lugogram_message, weblink: @lugogram_weblink, imagelink: @lugogram_imagelink, color: @lugogram_color %>
   		<div class="aftertext" style="margin-top: 30px;margin-bottom: 30px">
   		 <p style="font-size: 10px;color: gray">Enjoy your <a href="<%=@lugogram_url%>"><span style="font-size: 10px;color: gray">Lugogram</span></a>!
       </p>
      </div>	
   		<br/>
  </body>
</html>